{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute  html_class='full' placeholder=false()}
<div class="Form-field{if $attribute.has_validation_error} has-error{/if}">
    <label class="Form-label {if $attribute.is_required}is-required{/if}" for="ezcoa-{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}">
        {first_set( $contentclass_attribute.nameList[$content_language], $contentclass_attribute.name )|wash}
        {if $attribute.is_information_collector} <em class="collector">{'information collector'|i18n( 'design/admin/content/edit_attribute' )}</em>{/if}
        {if $attribute.is_required} ({'richiesto'|i18n('design/ocbootstrap/designitalia')}){/if}
    </label>

    {if $contentclass_attribute.description}
        <em class="attribute-description">{first_set( $contentclass_attribute.descriptionList[$content_language], $contentclass_attribute.description)|wash}</em>
    {/if}
    {def $anno_corrente = currentdate()|datetime( 'custom', '%Y' )
         $anno_pregresso = $anno_corrente|sub(10)
         $anni = array()}
    {for $anno_pregresso to $anno_corrente as $anno} 
        {set $anni = $anni|append($anno)}
    {/for}    
    {set $anni = $anni|reverse()}
    <select id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" 
            class="form-control ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" 
            name="{$attribute_base}_data_integer_{$attribute.id}">
        {foreach $anni as $anno}
        <option value="{$anno}" {if $attribute.data_int|eq( $anno )}selected="selected"{/if}>{$anno|wash( xhtml )}</option>
        {/foreach}
    </select>
    {undef $anno_corrente $anno_pregresso $anni}
</div>
{/default}

